query Footer {
  footer(where: { id: "clutp8sbo627g08w5jh00fyl9" }) {
    sponsorsTitle
    organizersTitle
    organizers {
      id
      logo {
        ...ImageFields
      }
    }
    sponsors {
      id
      logo {
        ...ImageFields
      }
      url
    }
  }
}
