query Footer {
  footer(where: { id: "clutp8sbo627g08w5jh00fyl9" }) {
    id
    sponsorsTitle
    organizersTitle
    logo {
      ...ImageFields
    }
    organizers {
      id
      logo {
        ...ImageFields
      }
    }
    sponsors {
      id
      logo {
        ...ImageFields
      }
      url
    }
  }
}
