query Footer($stage: Stage! = PUBLISHED) {
  footer(where: { id: "clutp8sbo627g08w5jh00fyl9" }, stage: $stage) {
    sponsorsTitle
    organizersTitle
    organizers {
      id
      url
      logo {
        ...ImageFields
      }
    }
    sponsors {
      id
      logo {
        ...ImageFields
      }
      alternativeLogo {
        ...ImageFields
      }
      url
    }
  }
}
