fragment CTAfields on Cta {
  id
  externalUrl
  style
  label
  socialMediaIcon
  linkedPage {
    slug
  }
}

fragment ImageFields on Asset {
  url
  width
  height
  fileName
}

fragment BannerFields on Banner {
  id
  title
  content {
    html
  }
  noBackground
  primaryCtas {
    ...CTAfields
  }
  secondaryCtas {
    ...CTAfields
  }
}

fragment HeroFields on Hero {
  id
  headline
  description
  backgroundImage {
    ...ImageFields
    image: url(
      transformation: {
        image: {
          resize: { width: 1440, height: 1000, fit: max }
          compress: { metadata: true }
          quality: { value: 80 }
        }
        document: { output: { format: autoImage } }
      }
    )
  }
  backgroundImageDarkness
  logoImage {
    url
  }
  ctas {
    ...CTAfields
  }
}

fragment ImageComponentFields on Image {
  id
  title
  image {
    ...ImageFields
  }
  ctAs {
    ...CTAfields
  }
}

fragment ImageGalleryFields on ImageGallary {
  id
  title
  images {
    ...ImageFields
  }
}

fragment NewsArticleFields on NewsArticle {
  id
  __typename
  slug
  title
  subtitle
  description
  slug
  image {
    ...ImageFields
  }
}

fragment SponsorFields on Sponsor {
  id
  __typename
  slug
  name
  tagline
  sponsorDescription
  url
  sponsorStatus
  logo {
    ...ImageFields
  }
  masterclass {
    slug
  }
}

fragment SessionFields on Session {
  id
  __typename
  title
  theme
  sessionTheme {
    theme
    color {
      hex
    }
  }
  speaker {
    name
    image {
      url
    }
  }
}

fragment SpeakerFields on Speaker {
  id
  __typename
  name
  description
  url
  image {
    ...ImageFields
  }
  sessions {
    ...SessionFields
  }
}

fragment ListFields on List {
  id
  title
  itemsPerRow
  linkedContent {
    ... on NewsArticle {
      ...NewsArticleFields
    }
    ... on Sponsor {
      ...SponsorFields
    }
    ... on Speaker {
      ...SpeakerFields
    }
    ... on Session {
      ...SessionFields
    }
  }
}

fragment ScheduleOverviewFields on ScheduleOverview {
  id
  title
  schedules {
    day
    slots {
      slot
      time
    }
  }
}

fragment TextFields on Text {
  id
  title
  titleType
  subtitle
  subtitleType
  content {
    html
  }
  ctas {
    ...CTAfields
  }
}

fragment TextMediaFields on TextMedia {
  id
  title
  mediaFirst
  media {
    ...ImageFields
  }
  text {
    ...TextFields
  }
}

fragment SupporterListFields on SupporterList {
  title
  supporters {
    id
    name
    link
  }
}

fragment SessionFormFields on SessionForm {
  id
  submitLabel
  title
  fields {
    id
    label
    required
    name
    placeholder
    sessionTypeSelector
  }
}
