fragment CTAfields on Cta {
  id
  externalUrl
  style
  label
  icon {
    url
  }
  linkedPage {
    slug
  }
}

fragment ImageFields on Asset {
  url
  width
  height
  fileName
}

fragment BannerFields on Banner {
  id
  title
  content {
    html
  }
  noBackground
  primaryCtas {
    ...CTAfields
  }
  secondaryCtas {
    ...CTAfields
  }
}

fragment HeroFields on Hero {
  id
  headline
  description
  backgroundImage {
    ...ImageFields
    image: url(
      transformation: {
        image: {
          resize: { width: 1440, height: 732, fit: crop }
          compress: { metadata: true }
          quality: { value: 100 }
        }
        document: { output: { format: autoImage } }
      }
    )
  }
  backgroundImageDarkness
  logoImage {
    url
  }
  ctas {
    ...CTAfields
  }
}

fragment ImageComponentFields on Image {
  id
  title
  image {
    ...ImageFields
  }
  ctAs {
    ...CTAfields
  }
}

fragment ImageGalleryFields on ImageGallary {
  id
  title
  images {
    ...ImageFields
  }
}

fragment NewsArticleFields on NewsArticle {
  id
  slug
  title
  subtitle
  description
  image {
    ...ImageFields
  }
}

fragment SponsorFields on Sponsor {
  id
  slug
  name
  sponsorDescription
  url
  sponsorStatus
  logo {
    ...ImageFields
  }
  masterclass {
    slug
  }
}

fragment ListFields on List {
  id
  linkedContent {
    ... on NewsArticle {
      ...NewsArticleFields
    }
    ... on Sponsor {
      ...SponsorFields
    }
  }
}

fragment ScheduleOverviewFields on ScheduleOverview {
  id
  title
  schedules {
    day
    slots {
      slot
      time
    }
  }
}

fragment TextFields on Text {
  id
  title
  titleType
  subtitle
  subtitleType
  content {
    html
  }
  ctas {
    ...CTAfields
  }
}

fragment TextMediaFields on TextMedia {
  id
  media {
    ...ImageFields
  }
  text {
    ...TextFields
  }
}
