query Navigation {
  navigation(where: { id: "cluqwbip82dc707w2m14gg677" }) {
    title
    navigationItem {
      id
      label
      externalLink
      highlighted
      page {
        slug
      }
    }
  }
}
