query NewsArticle($slug: String!) {
  newsArticle(where: { slug: $slug }) {
    __typename
    slug
    title
    subtitle
    description
    image {
      ...ImageFields
    }
    date
    components {
      __typename
      ... on Banner {
        ...BannerFields
      }
      ... on Hero {
        ...HeroFields
      }
      ... on Image {
        ...ImageComponentFields
      }
      ... on ImageGallary {
        ...ImageGalleryFields
      }
      ... on List {
        ...ListFields
      }
      ... on Text {
        ...TextFields
      }
      ... on TextMedia {
        ...TextMediaFields
      }
    }
  }
}
