query News($slug: String!, $stage: Stage! = PUBLISHED) {
  newsArticle(where: { slug: $slug }, stage: $stage) {
    __typename
    slug
    title
    subtitle
    description
    image {
      ...ImageFields
    }

    components(first: 100) {
      __typename
      ... on Banner {
        ...BannerFields
      }
      ... on Hero {
        ...HeroFields
      }
      ... on Image {
        ...ImageComponentFields
      }
      ... on ImageGallary {
        ...ImageGalleryFields
      }
      ... on List {
        ...ListFields
      }
      ... on ScheduleOverview {
        ...ScheduleOverviewFields
      }
      ... on Text {
        ...TextFields
      }
      ... on TextMedia {
        ...TextMediaFields
      }
      ... on SupporterList {
        ...SupporterListFields
      }
    }
  }
}
