query Page($slug: String!, $stage: Stage! = PUBLISHED) {
  page(where: { slug: $slug }, stage: $stage) {
    __typename
    slug
    openGraphTitle
    openGraphDescription
    openGraphImage {
      ...ImageFields
    }
    subPages {
      slug
    }
    parentPage {
      slug
    }
    components(first: 100) {
      __typename
      ... on Banner {
        ...BannerFields
      }
      ... on Hero {
        ...HeroFields
      }
      ... on Image {
        ...ImageComponentFields
      }
      ... on ImageGallary {
        ...ImageGalleryFields
      }
      ... on List {
        ...ListFields
      }
      ... on ScheduleOverview {
        ...ScheduleOverviewFields
      }
      ... on Text {
        ...TextFields
      }
      ... on TextMedia {
        ...TextMediaFields
      }
      ... on SupporterList {
        ...SupporterListFields
      }
    }
  }
}
