query Sponsor($slug: String!, $stage: Stage! = PUBLISHED) {
  sponsor(where: { slug: $slug }, stage: $stage) {
    __typename
    slug
    name
    sponsorDescription
    logo {
      ...ImageFields
    }
    sponsorStatus
    masterclass {
      slug
    }
  }
}
